os:
- linux
language: nix

env:
- LANG=C.utf8

script:
- nix-build
- mkdir -p site
- |-
  ./result/bin/ComiCal \
      --dc-issues         john-constantine-hellblazer-2019 \
      --dc-issues         strange-adventures-2020 \
      --image-collections gideon-falls \
      --image-collections lazarus \
      --image-collections pretty-deadly \
      --image-collections southern-bastards \
      --image-collections the-fix \
      --image-issues      ascender \
      --image-issues      bliss \
      --image-issues      family-tree \
      --image-issues      nailbiter \
      --image-issues      oblivion-song-by-kirkman-de-felici \
      --image-issues      spawn \
      >site/comics.ics

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: gh-pages
  local_dir: site
  on:
    branch: master
