os:
- linux
language: nix

env:
- LC_ALL=en_US.UTF-8

script:
- nix-env -iA cachix -f https://cachix.org/api/v1/install
- cachix use yurrriq
# TODO: - cachix push yurrriq --watch-store&
- nix-build release.nix
- mkdir -p site
- |-
  ./result/bin/ComiCal \
      --dc-issues         john-constantine-hellblazer-2019 \
      --dc-issues         supermans-pal-jimmy-olsen-2019 \
      --image-collections east-of-west \
      --image-collections gideon-falls \
      --image-collections lazarus \
      --image-collections outcast-by-kirkman-azaceta \
      --image-collections pretty-deadly \
      --image-collections southern-bastards \
      --image-collections the-fix \
      --image-issues      ascender \
      --image-issues      family-tree \
      --image-issues      oblivion-song-by-kirkman-de-felici \
      --image-issues      spawn \
      >site/comics.ics

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: gh-pages
  local_dir: site
  on:
    branch: master
