name: ComiCal
version: !include "./VERSION"
synopsis: Track the publish dates of your favorite comics
author: Eric Bailey
maintainer: eric@ericb.me
github: yurrriq/ComiCal
extra-source-files:
- CHANGELOG.md
dependencies:
- base
- bytestring
- exceptions
- lens
- modern-uri
- mtl
- optparse-applicative
- req
- tagsoup
- text
- time-compat
- transformers
default-extensions:
- OverloadedStrings
ghc-options:
- -Wall
- -Werror
- -fwarn-incomplete-patterns
library:
  source-dirs: src
  other-modules:
  - ComiCal.App
  - ComiCal.Util
  - Paths_ComiCal
executable:
  ghc-options:
  - -O2
  source-dirs: app
  main: Main.hs
  dependencies:
  - ComiCal
