name: ComiCal
version: !include "./VERSION"
synopsis: Track the publish dates of your favorite comics
author: Eric Bailey
maintainer: eric@ericb.me
github: yurrriq/ComiCal
extra-source-files:
- CHANGELOG.md
dependencies:
- aeson
- base
- mtl
default-extensions:
- OverloadedStrings
- TemplateHaskell
ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns
library:
  source-dirs: lib
  dependencies:
  - bytestring
  - composition-extra
  - exceptions
  - html-conduit
  - http-client
  - http-types
  - lens
  - modern-uri
  - monad-logger
  - req
  - tagsoup
  - text
  - time-compat
  - transformers
  - xml-conduit
executable:
  ghc-options:
  - -O2
  source-dirs: app
  main: Main.hs
  dependencies:
  - ComiCal
  - optparse-applicative
