name: ComiCal
version: 0.0.0.1
synopsis: Track the publish dates of your favorite comics
author: Eric Bailey
maintainer: eric@ericb.me
github: yurrriq/ComiCal
verbatim:
  cabal-version: 2.0
extra-source-files:
- CHANGELOG.md
dependencies:
- base >= 4.12
ghc-options:
- -Wall
- -Werror
library:
  ghc-options:
  - -fwarn-incomplete-patterns
  source-dirs: src
  exposed-modules: []
  dependencies: []
executable:
  ghc-options:
  - -O2
  source-dirs: app
  main: Main.hs
  dependencies:
  - ComiCal
