name: ComiCal
version: !include "./VERSION"
synopsis: Track the publish dates of your favorite comics
author: Eric Bailey
maintainer: eric@ericb.me
github: yurrriq/ComiCal
verbatim:
  cabal-version: 2.0
extra-source-files:
- CHANGELOG.md
dependencies:
- base >= 4.12
- bytestring >= 0.10
- modern-uri
- req
- text
- time
ghc-options:
- -Wall
- -Werror
library:
  ghc-options:
  - -fwarn-incomplete-patterns
  source-dirs: src
  exposed-modules:
  - Data.ComiCal
  dependencies:
  - tagsoup >= 0.14
executable:
  ghc-options:
  - -O2
  source-dirs: app
  main: Main.hs
  dependencies:
  - ComiCal
