name: ComiCal
version: !include "./VERSION"
synopsis: Track the publish dates of your favorite comics
author: Eric Bailey
maintainer: eric@ericb.me
github: yurrriq/ComiCal
extra-source-files:
- CHANGELOG.md
dependencies:
- base
- lens
- text
ghc-options:
- -Wall
- -Werror
library:
  ghc-options:
  - -fwarn-incomplete-patterns
  source-dirs: src
  exposed-modules:
  - Data.ComiCal
  - Data.ComiCal.Types
  other-modules:
  - Data.ComiCal.Parser
  - Paths_ComiCal
  dependencies:
  - bytestring
  - modern-uri
  - req
  - tagsoup
  - time
executable:
  ghc-options:
  - -O2
  source-dirs: app
  main: Main.hs
  dependencies:
  - ComiCal
