name: Build

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210126_f15f0b8/install
        extra_nix_config: |
          experimental-features = nix-command flakes
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/tarball/master
    - run: nix flake check
    - uses: cachix/cachix-action@v8
      with:
        name: yurrriq
        skipPush: true
    - run: |
        mkdir -p site
        nix run . -- \
            --dc-issues         american-vampire-1976-2020 \
            --dc-issues         batman-white-knight-presents-harley-quinn-2020 \
            --dc-issues         strange-adventures-2020 \
            --dc-issues         sweet-tooth-the-return-2020 \
            --image-collections gideon-falls \
            --image-collections lazarus \
            --image-collections pretty-deadly \
            --image-collections southern-bastards \
            --image-collections the-fix \
            --image-issues      ascender \
            --image-issues      bliss \
            --image-issues      family-tree \
            --image-issues      nailbiter \
            --image-issues      oblivion-song-by-kirkman-de-felici \
            --image-issues      spawn \
            --image-issues      the-department-of-truth \
            >site/comics.ics
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: site
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
