name: Build

on:
  push:
    branches:
    - main
  schedule:
  - cron: '0 7 1,15 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Nix
      uses: cachix/install-nix-action@v26
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: Check whether the flake evaluates
      run: nix flake check
    - uses: cachix/cachix-action@v15
      with:
        name: yurrriq
        skipPush: true
    - name: Update the calendar
      run: |
        mkdir -p site
        nix run . -- -p pull.json >site/comics.ics
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v4
      with:
        build_dir: site
        jekyll: false
        keep_history: true
        target_branch: gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
